# just manual: https://github.com/casey/just/#readme

# Runs clippy on the sources
check:
	cargo clippy

# Runs unit tests
test:
	cargo nextest run

# Finds unused dependencies
udeps:
	cargo udeps --all-targets --backend depinfo
